-- Create DATABASE
CREATE TABLE apl409_parts_master_nw_04(
    no VARCHAR(15) PRIMARY KEY,
    partNumber VARCHAR2(50),
    modelCdAnalysis VARCHAR2(50),
    ovrallRank VARCHAR2(50),
    suppProdRank VARCHAR2(50),
    pmTargtTpDom VARCHAR2(50),
    pmTargtTpOvrs VARCHAR2(50),
    partCategory VARCHAR2(50),
    ovPrdctFinYmd DATE,
    ovSuppFinYmd DATE,
    dmPrdctFinYmd DATE,
    dmInvFinSch DATE,
    dmNewLMtnStr DATE,
    dmInvFinDec DATE,
    dmSuppFinYmd VARCHAR2(50),
    dmSuppFinFlg VARCHAR2(50),
    emphaSontPartSate VARCHAR2(50),
    checkNo VARCHAR2(50),
    supplyPartNm VARCHAR2(50),
    newMdlInvtPic VARCHAR2(50),
    curInvtPic VARCHAR2(50),
    domesDlvLctTp VARCHAR2(50),
    ovseaDlvLctTp VARCHAR2(50)
)