name: BloomMaker CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Full directory tree:"
          tree || (apt-get update && apt-get install -y tree && tree)

      - name: Find package.json
        run: |
          echo "Searching for package.json files:"
          find . -name "package.json" -type f

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: |
            **/package.json
            **/package-lock.json

      - name: Navigate and Install
        run: |
          # Find the package.json location
          PACKAGE_JSON_PATH=$(find . -name "package.json" -type f | grep "bloommaker/apl102_scn_stock_nw_04" || echo "")

          if [ -z "$PACKAGE_JSON_PATH" ]; then
            echo "Error: Could not find package.json in the expected location"
            exit 1
          fi

          # Navigate to the directory containing package.json
          cd $(dirname "$PACKAGE_JSON_PATH")
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

          # Install dependencies
          npm ci

      - name: Run ESLint
        if: success()
        run: |
          PACKAGE_JSON_PATH=$(find . -name "package.json" -type f | grep "bloommaker/apl102_scn_stock_nw_04")
          cd $(dirname "$PACKAGE_JSON_PATH")
          npm run lint:check

      - name: Run tests
        if: success()
        run: |
          PACKAGE_JSON_PATH=$(find . -name "package.json" -type f | grep "bloommaker/apl102_scn_stock_nw_04")
          cd $(dirname "$PACKAGE_JSON_PATH")
          npm test
