name: BloomMaker CI/CD

on:
  push:
    paths:
      - "bloommaker/**"
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la bloommaker || echo "No bloommaker directory"
          ls -la bloommaker/apl102_scn_stock_nw_04 || echo "No apl102_scn_stock_nw_04 directory"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "**/package.json"

      - name: Install dependencies
        working-directory: bloommaker/apl102_scn_stock_nw_04
        run: |
          if [ -f "package.json" ]; then
            npm ci
          else
            echo "package.json not found"
            exit 1
          fi

      - name: Run tests
        working-directory: bloommaker/apl102_scn_stock_nw_04
        run: npm test
